[workspace]
members = [
  "aoc-2019",
  "aoc-2020",
  "aoc-2021",
  "aoc-2022",
  "aoc-2023"
]
default-members = ["aoc-2023"]
resolver = "2"

[workspace.dependencies]
aoc-main = { version = "0.5", features = ["bench"] }