[package]
name = "aoc-2019"
version = "0.1.0"
authors = ["Morley, Jonathan <jmorley@cvent.com>"]
edition = "2021"

[dependencies]
aoc-main = { workspace = true }
anyhow = "1.0.34"
itertools = "0.12.0"
