name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  verify:
    strategy:
      matrix:
        cmd: [test, clippy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run ${{ matrix.cmd }}
        run: cargo ${{ matrix.cmd }} --workspace
