name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  verify:
    strategy:
      matrix:
        cmd:
          - test --workspace
          - clippy --workspace
          - fmt --check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run ${{ matrix.cmd }}
        run: cargo ${{ matrix.cmd }}
